package com.nepalese.vigrovideoplayer.data.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nepalese.vigrovideoplayer.data.bean.Video;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VIDEO".
*/
public class VideoDao extends AbstractDao<Video, Long> {

    public static final String TABLENAME = "VIDEO";

    /**
     * Properties of entity Video.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Artist = new Property(2, String.class, "artist", false, "ARTIST");
        public final static Property Path = new Property(3, String.class, "path", false, "PATH");
        public final static Property ThumbPath = new Property(4, String.class, "thumbPath", false, "THUMB_PATH");
        public final static Property Resolution = new Property(5, String.class, "resolution", false, "RESOLUTION");
        public final static Property Size = new Property(6, long.class, "size", false, "SIZE");
        public final static Property Date = new Property(7, long.class, "date", false, "DATE");
        public final static Property Duration = new Property(8, long.class, "duration", false, "DURATION");
    }


    public VideoDao(DaoConfig config) {
        super(config);
    }
    
    public VideoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VIDEO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT UNIQUE ," + // 1: name
                "\"ARTIST\" TEXT," + // 2: artist
                "\"PATH\" TEXT," + // 3: path
                "\"THUMB_PATH\" TEXT," + // 4: thumbPath
                "\"RESOLUTION\" TEXT," + // 5: resolution
                "\"SIZE\" INTEGER NOT NULL ," + // 6: size
                "\"DATE\" INTEGER NOT NULL ," + // 7: date
                "\"DURATION\" INTEGER NOT NULL );"); // 8: duration
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VIDEO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Video entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String artist = entity.getArtist();
        if (artist != null) {
            stmt.bindString(3, artist);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(4, path);
        }
 
        String thumbPath = entity.getThumbPath();
        if (thumbPath != null) {
            stmt.bindString(5, thumbPath);
        }
 
        String resolution = entity.getResolution();
        if (resolution != null) {
            stmt.bindString(6, resolution);
        }
        stmt.bindLong(7, entity.getSize());
        stmt.bindLong(8, entity.getDate());
        stmt.bindLong(9, entity.getDuration());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Video entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String artist = entity.getArtist();
        if (artist != null) {
            stmt.bindString(3, artist);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(4, path);
        }
 
        String thumbPath = entity.getThumbPath();
        if (thumbPath != null) {
            stmt.bindString(5, thumbPath);
        }
 
        String resolution = entity.getResolution();
        if (resolution != null) {
            stmt.bindString(6, resolution);
        }
        stmt.bindLong(7, entity.getSize());
        stmt.bindLong(8, entity.getDate());
        stmt.bindLong(9, entity.getDuration());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Video readEntity(Cursor cursor, int offset) {
        Video entity = new Video( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // artist
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // path
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // thumbPath
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // resolution
            cursor.getLong(offset + 6), // size
            cursor.getLong(offset + 7), // date
            cursor.getLong(offset + 8) // duration
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Video entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setArtist(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPath(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setThumbPath(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setResolution(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSize(cursor.getLong(offset + 6));
        entity.setDate(cursor.getLong(offset + 7));
        entity.setDuration(cursor.getLong(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Video entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Video entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Video entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
